## Import the __`numpy`__ package

In [3]:
import numpy as np

## Create a vector of ten zeros

In [ ]:
v = np.zeros(10)
v

## Create a vector of size ten with nine zeros and a 1 in the fifth position

In [ ]:
v = np.zeros(10)
v[4] = 1
v

## Create a vector with values ranging from 10 to 49

In [ ]:
v = np.arange(10, 50)
v

## Reverse the previous vector

In [ ]:
v[::-1]

## Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
m = np.arange(0, 9).reshape(3, 3)
m

## Find the indices of the non-zero elements of the following array:

In [1]:
v = [1, 2, 0, 0, 4, 0] # Given

In [4]:
np.nonzero(v)

(array([0, 1, 4]),)

## Create a 3x3x3 array with random values

In [ ]:
a = np.random.random((3, 3, 3))
a

## Find the minimum and maximum values generated in the previous step

In [ ]:
a.min(), a.max()

## Create a vector with 30 random values and find its mean

In [ ]:
v = np.random.random(30)
v.mean()

## Try to predict the output of each of the following cells before running them

In [ ]:
0 * np.nan

In [ ]:
np.nan == np.nan

In [ ]:
np.inf > np.nan

In [ ]:
np.nan - np.nan

In [6]:
0.3 == 3 * 0.1

False

In [ ]:
np.array(0) // np.array(0)

In [5]:
np.array(0) // np.array(0.)

nan

In [ ]:
np.array(0) / np.array(0)

In [ ]:
np.array(0) / np.array(0.)

## Find the integer part of the following array

In [7]:
a = np.random.uniform(0, 10, 10)
a

array([8.38980499, 1.46821367, 8.87262988, 3.1867649 , 5.77856325,
       1.19042607, 1.05673242, 3.5577573 , 8.27709934, 2.60306884])

In [ ]:
a.astype(int)

In [ ]:
np.floor(a)

In [ ]:
np.ceil(a) - 1

In [ ]:
np.trunc(a)

## Create a vector of 10 values from 0 to 1, both included

In [8]:
v = np.linspace(0, 1, 10)
v

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

## Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [ ]:
v = np.linspace(0, 1, 12)[1:-1]
v

## Add 1,000,000 numbers together using __`numpy`__ vectorized operations

In [ ]:
v = np.random.random(1_000_000)
np.sum(v)

## Create a 4x4 array of the first 16 powers of 3

In [9]:
a = np.arange(16).reshape((4, 4))
3 ** a

array([[       1,        3,        9,       27],
       [      81,      243,      729,     2187],
       [    6561,    19683,    59049,   177147],
       [  531441,  1594323,  4782969, 14348907]])